# 公共配置文件
spring:
  application:
    name: memory-search
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000

  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/memory_search?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: Dw990831

    # Redis 配置
    # todo 需替换配置，然后取消注释
  redis:
    database: 3
    host: localhost
    port: 6379

  # Elasticsearch 配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456

  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB

knife4j:
  enable: true
  openapi:
    title: MemorySearch 忆搜阁 接口文档
    description: MemorySearch 忆搜阁
    concat: 3348407547@qq.com
    url: https://deng-2022.gitee.io/blog/
    version: 1.0
    license: Apache 2.0
    group:
      test1:
        group-name: memory-search

server:
  address: 0.0.0.0
  port: 8104
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
